### ISSUE TITLE
Work needed to achieve real time rendering?

### ISSUE THREAD

**Issue by ghost** [Wunkolo/vkblam#3]
Just curious on how much/what work would need to be done to achieve realtime rendering in a window with WASD/Mouse camera controls

**Comment by Wunkolo** [comment]
Not much work at all honestly. Just a glfw window context and input processing to control a `vkblam::SceneView`-"camera" object. Right now though I am just trying to re-implement the core rendering tech and have no need for a real-time interactive window but I am designing my code in such a way that lends itself to it.

**Comment by ghost** [comment]
That's what I love to hear! In that case I have a follow up question then. If I wish to help contribute with this project what would you prefer me to work on?

**Comment by Wunkolo** [comment]
Thank you for your interest:

There is much to do as far as re-implementing the blam's rendering system.

Right now I am reverse engineering the Halo executable to try and get a clear picture of the extent in which [halo's many shader tags](https://c20.reclaimers.net/h1/tags/shader/) are utilized across the engine so I have a clear idea as to how to architect my own shader-system to handle all of the shaders and their many permutations as up-front as possible.

Any help in mapping out Halo's tag structures would be helpful as well. [As there are a lot of unknowns and TagBlocks that should be filled in](https://github.com/Wunkolo/vkblam/blob/66d9fb9d1f753edb75b7b533a330372fb0bc5968/include/Blam/Tags.hpp).

Much of this information is researched already in other projects and just has to be put into a `struct` like I have for the others there. 

If you have knowledge in regard to the blam engine to aid in the above and to fill in any gaps in knowledge that isn't already in the codebase, then that would help. Otherwise, some UX help that would benefit the current development-environment would be useful.

Like picking which GPU to render upon rather than just picking the first:
https://github.com/Wunkolo/vkblam/blob/66d9fb9d1f753edb75b7b533a330372fb0bc5968/source/main.cpp#L140-L170

Taking some of these "magic numbers" into something like a config file:
https://github.com/Wunkolo/vkblam/blob/66d9fb9d1f753edb75b7b533a330372fb0bc5968/source/main.cpp#L44
https://github.com/Wunkolo/vkblam/blob/66d9fb9d1f753edb75b7b533a330372fb0bc5968/include/VkBlam/VkBlam.hpp#L25-L26

[Updating some of the vulkan utility structures such that they are thread-safe](https://github.com/Wunkolo/vkblam/tree/main/source/Vulkan).

Some error handling in the case that vkblam is trying to load a map that it does not support just yet.

If you have access to an Apple device or any other non-windows non-linux device that supports vulkan, I would also like to ensure compatibility with [MoltenVK](https://github.com/KhronosGroup/MoltenVK) and such to ensure that I am writing portable Vulkan code.

There is much else that could be done but be sure to try and scope the task in a github issue before giving it any work-time to both keep track of the tasks involved as well as determine if this is not something that is already being designed on my part.

**Comment by ghost** [comment]
Sure, I'll see what I can do, when I can. Appreciate the detailed response
